version: '3'

services:
  nginx-proxy:
    image: nginx:1.18.0
    container_name: nginx-proxy
    restart: always
    ports:
      - "880:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./out/:/var/www/front/
